### ISSUE TITLE
Submit `jhu_ntap`

### ISSUE THREAD

**Issue by anngvu** [nf-osi/datahub#1]
Before creating a PR to upstream, the following issues in [validation results](https://github.com/nf-osi/datahub/blob/newstudy/nfosi_2022/public/mixed_nfosi_2022/html_report/mixed_nfosi_2022-validation.html) need to be resolved/clarified:

Notes: 
- (With `pwd` being the `public` folder), validation run using `docker run --rm -v $(pwd):/datahub cbioportal/cbioportal:4.1.13 validateStudies.py -d /datahub -l mixed_nfosi_2022 -u http://cbioportal.org -html /datahub/mixed_nfosi_2022/html_report`  
- Generate case lists: 
```
GCL=path/to/directory/with/script
python2 $GCL/generate_case_lists.py -c $GCL/case_list_conf.txt -d case_lists -s . -i mixed_nfosi_2022 -o
```

- [x] Validate with suitable version of image - @anngvu 
- [x] Config for public cBioPortal requires a different genome reference for `maf` - @jaybee84 
- [x] Don't forget to generate case list -- minor issue - @anngvu 
- [x] Either rename patient id to disambiguate from cell line from patient or remove the cell line data?

Other issues, i.e. these don't directly affect validation results but need to be resolved
- [x] Create mirror issue in cBioPortal/datahub
- [x] Should HTML validation file be kept in the folder or moved elsewhere?
- [x] Official citation for citation field?
- [x] What LICENSE file to use?
- [x] Lobby for adding Plexiform Neurofibroma. Doesn't affect validation since we're technically using "mixed" cancer type currently.

**Comment by allaway** [comment]
License: CC0 is likely what DSP says, but @jaybee84  can present the options to JHU Biobank PI to confirm preference. 
Citation: Should probably be the sci data manuscript for JHU Biobank.

**Comment by jaybee84** [comment]
Genome reference conversation is being tracked in the JIRA issue: https://sagebionetworks.jira.com/browse/WORKFLOWS-250

**Comment by jaybee84** [comment]
Official citation: https://www.nature.com/articles/s41597-020-0508-5

**Comment by jaybee84** [comment]
LICENSE : Creative Commons Attribution 4.0 International License 
(as mentioned in the associated publication: https://www.nature.com/articles/s41597-020-0508-5#rightslink)

**Comment by allaway** [comment]
I think that license refers to the publication, not the data, but maybe I am misunderstanding it?

**Comment by jaybee84** [comment]
My understanding is that the data released through the publication also falls under the same license as the article which says free to share, adapt, and build upon as long as you provide attribution to the author. Any component that has requirements that exceed the article's license needs user to reach out to the original group directly.
