### ISSUE TITLE
Update `jhu_ntap` (Hirbe) datataset

### ISSUE THREAD

**Issue by anngvu** [nf-osi/datahub#2]
Issue to track updating hirbe dataset previous submitted (#1). (Note: the curators assigned the directory name `nst_nfosi_ntap`, this dataset is referenced as `jhu` because that is easier for us to remember.)

### Changelog / Notes

(most recent changes on top)

- Revise dataset to remove samples below, update case list again
- Create first pass staging dataset, send out case list to confirm -- should remove JH-2-084 and JH-2-106
- (Clinical data) ~Use most updated clinical data: syn53354432~  Replace with even more up-to-date Biobank-batch1234-NF1status-Stavriani-10272023.xlsx - syn53646453 
- (RNA-seq gene expression) Add counts from https://www.synapse.org/#!Synapse:syn53141534.1/datasets/
- (MAF) Use updated MAFs from https://www.synapse.org/#!Synapse:syn51907770

### Checklist

- [x] Format and replace with files noted in changelog
- [x] Regenerate case list
`GCL=path/to/directory/with/script
python2 $GCL/generate_case_lists.py -c $GCL/case_list_conf.txt -d case_lists -s . -i nst_nfosi_ntap -o`
- [x] Validate with suitable version of images
`docker run --rm -v $(pwd):/datahub cbioportal/cbioportal:4.1.13 validateStudies.py -d /datahub -l nst_nfosi_ntap -u http://cbioportal.org -html /datahub/nst_nfosi_ntap/html_report`
- [x] Get approval
- [x] Create mirror issue in cBioPortal/datahub (cBioPortal requirement): https://github.com/cBioPortal/datahub/issues/2034
- [x] Make PR that passes checks: https://github.com/cBioPortal/datahub/pull/2035

**Comment by anngvu** [comment]
### Changelog / Notes

(most recent changes on top)

### Update submission

- (Clinical data) Replace with even more up-to-date Biobank-batch1234-NF1status-Stavriani-10272023.xlsx - syn53646453 
- (Clinical data) Use most updated clinical data: syn53354432 
- (RNA-seq gene expression) Add counts from https://www.synapse.org/#!Synapse:syn53141534.1/datasets/
- (MAF) Add samples from https://www.synapse.org/#!Synapse:syn52789072.1/datasets/

### First submission

- (Clinical data) Use basic clinical data
- (MAF) Merged MAF

**Comment by anngvu** [comment]
@jaybee84 Closing this, we can start watching the PR https://github.com/cBioPortal/datahub/pull/2035.

**Comment by jaybee84** [comment]
Just want to mention that this refers to the JHU Biobank dataset which is from Christine Pratilas's Lab in Hopkins. They collaborated with Dr. Angela Hirbe for data generation. So maybe calling it Pratilas dataset (instead of Hirbe dataset) would reduce confusion going forward.
